#!/bin/sh

move2trash () {
  BASENAME=${1##*/}
  if [ -d $1 ]; then
    mv "$1" "${HOME}/.Trash/${BASENAME}-${RANDOM}"
  fi
}

yarn cache clean && \

move2trash yarn.lock && \
move2trash package-lock.json && \
move2trash dll && \
move2trash app/dist/ && \
move2trash node_modules && \

yarn build
jest --clearCache
echo "Ready you can start again!"
